use Demo

CREATE TABLE [dbo].[Receiver](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[MobilePhone] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_ReceiverId] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[SMSMessage](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ReceiverId] [int] NOT NULL,
	[SentDateTime] [datetime2](7) NOT NULL,
	[FileName] [nvarchar](55) NOT NULL,
 CONSTRAINT [PK_SMSMessageId] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SMSMessage]  WITH CHECK ADD  CONSTRAINT [FK_ReceiverSMSMessage] FOREIGN KEY([ReceiverId])
REFERENCES [dbo].[Receiver] ([Id])
GO

ALTER TABLE [dbo].[SMSMessage] CHECK CONSTRAINT [FK_ReceiverSMSMessage]
GO